"""Change int to bool

Revision ID: 3971b3109778
Revises: af5a2a4f3307
Create Date: 2026-01-03 11:32:52.030381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3971b3109778'
down_revision = 'af5a2a4f3307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.alter_column('is_manager',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_manager',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_admin',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
