"""init migrate

Revision ID: 5451c5df0ba3
Revises:
Create Date: 2024-06-18 18:20:28.406410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5451c5df0ba3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('texture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('bitter', sa.Integer(), nullable=True),
    sa.Column('salty', sa.Integer(), nullable=True),
    sa.Column('sour', sa.Integer(), nullable=True),
    sa.Column('sweet', sa.Integer(), nullable=True),
    sa.Column('umami', sa.Integer(), nullable=True),
    sa.Column('fat', sa.Integer(), nullable=True),
    sa.Column('piquant', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Integer(), nullable=True),
    sa.Column('color1', sa.String(), nullable=True),
    sa.Column('color2', sa.String(), nullable=True),
    sa.Column('color3', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emotion_dish',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['emotion.id'], )
    )
    op.create_table('shape_dish',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['shape.id'], )
    )
    op.create_table('texture_dish',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['dish.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['texture.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('texture_dish')
    op.drop_table('shape_dish')
    op.drop_table('emotion_dish')
    op.drop_table('dish')
    op.drop_table('texture')
    op.drop_table('shape')
    op.drop_table('menu')
    op.drop_table('emotion')
    # ### end Alembic commands ###
