"""add_is_manager

Revision ID: 7ca8685c0b0c
Revises: 81c9982cf9c3
Create Date: 2026-01-02 12:25:10.780714

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ca8685c0b0c"
down_revision = "81c9982cf9c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_manager", sa.Integer(), nullable=False, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("is_manager")

    # ### end Alembic commands ###
