"""add_menu_owner

Revision ID: 81c9982cf9c3
Revises: acc66ee6b3e5
Create Date: 2026-01-02 12:11:52.996106

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "81c9982cf9c3"
down_revision = "acc66ee6b3e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("menu", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_menu_owner_id", "user", ["owner_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("menu", schema=None) as batch_op:
        batch_op.drop_constraint("fk_menu_owner_id", type_="foreignkey")
        batch_op.drop_column("owner_id")

    # ### end Alembic commands ###
