"""add_user_email

Revision ID: af5a2a4f3307
Revises: 6097b758f473
Create Date: 2026-01-02 17:45:31.328837

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af5a2a4f3307"
down_revision = "6097b758f473"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_log", schema=None) as batch_op:
        batch_op.alter_column("status_code", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(), nullable=True))
        batch_op.create_unique_constraint("uq_user_email", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_email", type_="unique")
        batch_op.drop_column("email")

    with op.batch_alter_table("request_log", schema=None) as batch_op:
        batch_op.alter_column("status_code", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
